### ISSUE TITLE
difference between https://github.com/apache/cordova-plugin-geolocation

### ISSUE THREAD

**Issue by cquezpro** [zhouzhongyuan/cordova-plugin-geolocation-baidu#3]
Hello.
I'd like to know difference between this repo and https://github.com/apache/cordova-plugin-geolocation

Thanks

**Comment by zhouzhongyuan** [comment]
**Improve geoloaction accuracy in China mainland**

Most Android phones made by Xiaomi, Huawei, Meizu(used by people in **China mainland**) can **NOT** get the geoloaction precisely. Because these phone manufacturers will modify the kernel of android, delete android's default location service.

If you want to get a  precise location in China mainland, you have to no choice but use Baidu Location SDK or GaoDe Location SDK.

What I did is change the `getCurrentPosition` method  from get loaction by android's default method to get loaction by Baidu Loaction SDK.

If your users are not in china mainland, don't care about my repo, just use [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation).
